replicaCount: 3

image:
  repository: 586794438876.dkr.ecr.us-east-2.amazonaws.com/search-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  loadBalancerType: "nlb"  
  port: 443
  targetPort: 8000
  securityGroup: "sg-0587a0baee3f6796d"
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
    "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:us-east-2:586794438876:certificate/2052b6b6-a563-4b7e-8065-12b84e2d62d1"
    "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443"
  forceRedeploy: true
env:
  PAGERDUTY_ROUTING_KEY: "979cbd4c3fbd4c07c0e604da32a0d9ff"
