name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}:latest api/

      # Tag the image with the ECR repository URI
      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.AWS_ECR_REGISTRY }}:latest ${{ secrets.AWS_ECR_URI }}:latest

      # Push the Docker image to ECR
      - name: Push to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_URI }}:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name etechapp-eks-uKDGKMvN
          helm upgrade --install search-api helm/
